server:
    port: 8080

spring:
  application:
    name: identification

eureka:
#客户端
  client:
#注册中心地址
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
    security:
# 仅限于 开发环境可对security进行关闭。
        enabled: false
    metrics:
        export:
            prometheus:
                enabled: true
                step: 1m
                descriptions: true
    web:
        server:
            auto-time-requests: true
    endpoints:
        web:
            exposure:
                include: health,info,env,prometheus,metrics,httptrace,threaddump,heapdump
